/**
 * <pvnc>
 *     reason: Centralise Provenance standing instructions in .pvnc/PROVENANCE.md and write only a short pointer into CLAUDE.md / copilot / cursor files, so instruction updates never require touching user-managed files
 *     source: ai.claude
 * </pvnc>
 */
import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';

// ── Sentinels ─────────────────────────────────────────────────────────────────

// Detect files already configured under the old (full-instructions) scheme.
const SENTINEL_V1 = 'provenance — standing instructions';
// Detect files already configured under the new (pointer) scheme.
const SENTINEL_V2 = '.pvnc/PROVENANCE.md';

function hasProvenance(content: string): boolean {
  return content.includes(SENTINEL_V1) || content.includes(SENTINEL_V2);
}

// ── Pointer line written into CLAUDE.md / copilot / cursor ───────────────────

const POINTER = `\
<!-- provenance-pointer -->
> [!IMPORTANT]
> **Provenance** — Read \`.pvnc/PROVENANCE.md\` before modifying any code in this repository.
> That file contains annotation rules, Code Guard instructions, and what not to do.
> It is auto-maintained by the Provenance VS Code extension — do not delete it.
<!-- /provenance-pointer -->
`;

// ── Canonical instruction file written to .pvnc/PROVENANCE.md ────────────────

export const PROVENANCE_MD = `\
<!--
  Auto-generated by the Provenance VS Code extension.
  Do not edit this file manually — it will be overwritten on next activation.
  To update the instructions, update the Provenance extension.
-->

# Provenance — standing instructions

This project uses the Provenance annotation convention to embed traceability
directly into source code. Follow these rules on every code change, without
being asked.

## When modifying existing code

1. Read all \`<pvnc>\` / \`<provenance>\` blocks that annotate the code you are
   about to change before making any edits.
2. After making the change, add a **new** \`<pvnc>\` block immediately before
   the affected line or method. Never replace or remove existing blocks.
3. The new block must include:
   - A ticket reference using the system name as the key: \`github: 123\`,
     \`jira: PROJ-42\`, \`ado: 45678\`. If no ticket exists, omit the ticket line.
   - \`reason:\` — one sentence describing *why* the change was made (not what).
   - \`source:\` — \`human\`, \`ai.claude\`, \`ai.copilot\`, etc.
4. If the changed code must not be simplified in future, add \`do-not-change:\` with
   a short justification.

## When adding new code

Add a \`<pvnc>\` block immediately before the new function, method, or
logical block. Same fields as above.

## Annotation format

\`\`\`typescript
/**
 * <pvnc>
 *     github: 123
 *     reason: Plain English explanation of why this code exists or changed
 *     source: ai.claude
 * </pvnc>
 */
\`\`\`

Any ticket system name is a valid key (\`jira\`, \`ado\`, \`linear\`, \`confluence\`, …).
Adjust the comment style to match the language (\`/** */\` for Java/TS/JS,
\`# ...\` for Ruby/shell, etc.). Always indent the keys by 4 spaces inside the
tags. Both \`<pvnc>\` and \`<provenance>\` are valid tag names.

## What not to do

- Do not remove or rewrite existing \`<pvnc>\` / \`<provenance>\` blocks.
- Do not add annotations to lines you did not change.
- Do not remove or simplify code marked with \`do-not-change\` without explicit instruction.

## Code Guard rules

Code Guard regions are marked with \`pvnc.guard_start: <block-id>\` and
\`pvnc.guard_end: <block-id>\` line comments. They protect code that must not
change without an explicit audit trail.

1. Never modify code between \`pvnc.guard_start\` and \`pvnc.guard_end\` markers.
2. If asked to modify a guarded region, inform the user and request explicit
   confirmation referencing the block ID before proceeding.
3. If proceeding with permission, the **first** commit must contain only the
   removal declaration — no code changes:
   \`pvnc.guard_removed: <block-id> : <reason>\`
4. The **second** commit makes the change. Optionally replace the guard with a
   new \`pvnc.guard_start\`/\`pvnc.guard_end\` block using a new block ID and
   an accompanying \`<pvnc>\` annotation.

### Example guard

\`\`\`python
# <pvnc>
#     jira: HMRC-001
#     reason: HMRC 2026-Q1 food exemption rules — audited annually
#     do-not-change: HMRC compliance
#     source: human
# </pvnc>
# pvnc.guard_start: block-hmrc-001
if order.category == "food" and order.sugar_content <= 2:
    tax = 0.0
# pvnc.guard_end: block-hmrc-001
\`\`\`
`;

// ── Target agent files ────────────────────────────────────────────────────────

interface TargetFile {
  rel: string;
  label: string;
}

const TARGETS: TargetFile[] = [
  { rel: 'CLAUDE.md',                          label: 'Claude Code' },
  { rel: '.github/copilot-instructions.md',    label: 'GitHub Copilot' },
  { rel: '.cursorrules',                       label: 'Cursor' },
];

// ── Public helpers ────────────────────────────────────────────────────────────

/** Write (or overwrite) .pvnc/PROVENANCE.md with the current canonical instructions. */
export function writeProvenanceMd(root: string): void {
  const pvncDir = path.join(root, '.pvnc');
  if (!fs.existsSync(pvncDir)) fs.mkdirSync(pvncDir, { recursive: true });
  fs.writeFileSync(path.join(pvncDir, 'PROVENANCE.md'), PROVENANCE_MD, 'utf8');
}

/**
 * Replace the pointer block in-place if present, or prepend it if missing.
 * Returns 'replaced' | 'prepended' | 'unchanged' for reporting.
 */
function resetPointerInFile(abs: string): 'replaced' | 'prepended' | 'created' {
  const BLOCK_RE = /<!-- provenance-pointer -->[\s\S]*?<!-- \/provenance-pointer -->\n?/;

  if (!fs.existsSync(abs)) {
    fs.writeFileSync(abs, POINTER, 'utf8');
    return 'created';
  }

  const existing = fs.readFileSync(abs, 'utf8');

  if (BLOCK_RE.test(existing)) {
    fs.writeFileSync(abs, existing.replace(BLOCK_RE, POINTER), 'utf8');
    return 'replaced';
  }

  // Block is gone entirely — prepend it.
  const sep = existing.startsWith('\n') ? '' : '\n';
  fs.writeFileSync(abs, POINTER + sep + existing, 'utf8');
  return 'prepended';
}

// ── Commands ──────────────────────────────────────────────────────────────────

export async function resetInstructions(): Promise<void> {
  const workspaceFolders = vscode.workspace.workspaceFolders;
  if (!workspaceFolders?.length) {
    vscode.window.showErrorMessage('Provenance: No workspace folder open.');
    return;
  }

  const root = workspaceFolders[0].uri.fsPath;

  // Always refresh the canonical file.
  writeProvenanceMd(root);

  const results: string[] = [];

  for (const target of TARGETS) {
    const abs = path.join(root, target.rel);
    const dir = path.dirname(abs);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    const outcome = resetPointerInFile(abs);
    const verb = outcome === 'created' ? 'created' : outcome === 'replaced' ? 'refreshed' : 'restored';
    results.push(`${target.label} (${verb})`);
  }

  const action = await vscode.window.showInformationMessage(
    `Provenance: Reset complete — ${results.join(', ')}. .pvnc/PROVENANCE.md refreshed.`,
    'Open files',
  );

  if (action === 'Open files') {
    for (const target of TARGETS) {
      const abs = path.join(root, target.rel);
      const doc = await vscode.workspace.openTextDocument(abs);
      await vscode.window.showTextDocument(doc, { preview: false });
    }
  }
}

export async function setupInstructions(): Promise<void> {
  const workspaceFolders = vscode.workspace.workspaceFolders;
  if (!workspaceFolders?.length) {
    vscode.window.showErrorMessage('Provenance: No workspace folder open.');
    return;
  }

  const root = workspaceFolders[0].uri.fsPath;

  // Always refresh the canonical file first.
  writeProvenanceMd(root);

  const created: string[] = [];
  const updated: string[] = [];
  const skipped: string[] = [];

  for (const target of TARGETS) {
    const abs = path.join(root, target.rel);
    const dir = path.dirname(abs);

    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    if (!fs.existsSync(abs)) {
      // New file — write just the pointer.
      fs.writeFileSync(abs, POINTER, 'utf8');
      created.push(target.label);
      continue;
    }

    const existing = fs.readFileSync(abs, 'utf8');

    if (hasProvenance(existing)) {
      skipped.push(target.label);
      continue;
    }

    // Existing file with no Provenance entry — prepend the pointer so agents
    // see it at the top before any other content.
    const separator = existing.startsWith('\n') ? '' : '\n';
    fs.writeFileSync(abs, POINTER + separator + existing, 'utf8');
    updated.push(target.label);
  }

  const parts: string[] = [];
  if (created.length) parts.push(`Created: ${created.join(', ')}.`);
  if (updated.length) parts.push(`Updated: ${updated.join(', ')}.`);
  if (skipped.length) parts.push(`Already configured (skipped): ${skipped.join(', ')}.`);

  const touched = [...created, ...updated];
  const message = parts.join(' ');

  if (touched.length === 0) {
    vscode.window.showInformationMessage(`Provenance: ${message}`);
    return;
  }

  const action = await vscode.window.showInformationMessage(
    `Provenance: ${message}`,
    'Open files',
  );

  if (action === 'Open files') {
    for (const target of TARGETS) {
      const abs = path.join(root, target.rel);
      if (touched.includes(target.label)) {
        const doc = await vscode.workspace.openTextDocument(abs);
        await vscode.window.showTextDocument(doc, { preview: false });
      }
    }
  }
}
